### ISSUE TITLE
Show the EDNS Client Subnet (ECS) option

### ISSUE THREAD

**Issue by sevencastles** [dmachard/dns-collector#23]
Hi @dmachard ,
first of all, thank you for this tool, it's really powerful. 

I am interested in seeing the EDNS Client Subnet (ECS) option of the queries I log. Can you add it this info to the loggers? Alternatively, can you add support to see the full "query_message" (so I can see the ECS inside the message) or the DNS query options?

Thanks,
Carlo

**Comment by dmachard** [comment]
This feature will be implemented in the next release

**Comment by sevencastles** [comment]
awesome, thank you!

**Comment by dmachard** [comment]
A new [beta](https://github.com/dmachard/dns-collector/releases/tag/v0.14.0-b4) release is available.
The CSUBNET can be added in text format with the directive "edns-csubnet" 

```
2021-12-27T14:15:22.811687512Z dnsdist1 CLIENT_QUERY NOERROR 192.168.1.210 42293 INET UDP 61b google.com A 0.000000 192.128.0.0/10
2021-12-27T14:15:22.832947566Z dnsdist1 CLIENT_RESPONSE NOERROR 192.168.1.210 42293 INET UDP 145b google.com A 0.021260 192.128.0.0/10
```

It's also available in the JSON format:
```

  "edns": {
    "udp-size": 512,
    "rcode": 0,
    "version": 0,
    "dnssec-ok": 0,
    "options": [
      {
        "code": 8,
        "name": "CSUBNET",
        "data": "192.128.0.0/10"
      }
    ]
  },
```

Any feedback will be appreciated regarding this feature.

**Comment by sevencastles** [comment]
So far so good. Soon I will be able to do more extensive tests.

**Comment by dmachard** [comment]
The release 0.14.0 is available :) I am interested to know If you can share your use case and what you plan to do with it
