### ISSUE TITLE
Resolve ip to ASN

### ISSUE THREAD

**Issue by KVInventoR** [dmachard/dns-collector#4]
Hi @dmachard 

First of all, I would like to say: thank you for this wonderful new collector, it works really well and collector has really good performance.
I would like to ask you about new feature, which probably is not related exactly to collector directly, but really useful for us to develop new feature for block dns attach from some specific ASN.

It will be really useful to have some additional information about top source ip requesters which will include also subnet range from whois and asn information as additional labels:

https://github.com/ammario/ipisp

also, I guess it will raise a performance issue and probably one of the solution will be integrate go-dnscollector with redis db for some cache options.

**Comment by dmachard** [comment]
this project can help too https://github.com/jedisct1/iptoasn-webservice

**Comment by dmachard** [comment]
What do you think about the GeoLite2-ASN database ?
I ask that because it's easy to integrate.

**Comment by KVInventoR** [comment]
I am totally fine, 
just need to get info, which will give possibility to block bot net requests.
It's really cool, when it possible to have statistics not only for ips, but also for ASN number and ASN owner.

**Comment by KVInventoR** [comment]
It's also will be helpful to have top ASN requesters with top ASN owners  to get over /metrics

**Comment by dmachard** [comment]
A new beta is available with the docker tag 0.14.0-b.
Any feedback will be appreciated regarding performance and the GeoIP feature.

A new feature is available with [Loki+Grafana](https://dmachard.github.io/posts/0044-dnscollector-grafana-loki/), if you are interested I will appreciate returns

**Comment by KVInventoR** [comment]
thank you for this new wonderful changes, I see some changes, but doesn't see something like: top ASN requestors
I see new metrics, like:
```
dnscollector_as_numbers_total{stream="global"} 1
dnscollector_as_numbers_top_total{stream="global",domain="-"} 119771
dnscollector_as_owners_total{stream="global"} 1
dnscollector_as_owners_top_total{stream="global",domain="-"} 119771
dnscollector_as_numbers_total{stream="dns-cache01"} 1
dnscollector_as_numbers_top_total{stream="dns-cache01",domain="-"} 104004
dnscollector_as_owners_total{stream="dns-cache01"} 1
dnscollector_as_owners_top_total{stream="dns-cache01",domain="-"} 104004
dnscollector_as_numbers_total{stream="dns-cache02"} 1
dnscollector_as_numbers_top_total{stream="dns-cache02",domain="-"} 15767
dnscollector_as_owners_total{stream="dns-cache02"} 1
dnscollector_as_owners_top_total{stream="dns-cache02",domain="-"} 15767
```

**Comment by KVInventoR** [comment]
> A new beta is available with the docker tag 0.14.0-b1. Any feedback will be appreciated regarding performance and the GeoIP feature.
> 
> A new feature is available with [Loki+Grafana](https://dmachard.github.io/posts/0044-dnscollector-grafana-loki/), if you are interested I will appreciate returns

this is really good, because before I used store logs in memory drive and grafana-agent to with promtail to read logs and push them to loki
I will try to use directly push logs to loki

**Comment by KVInventoR** [comment]
this magic project will be similar to: https://fastnetmon.com/ 

just need to implement ML and notifications to detect attacks 
after that, you will be sell this project to big companies
really good job

**Comment by dmachard** [comment]
> thank you for this new wonderful changes, I see some changes, but doesn't see something like: top ASN requestors I see new metrics, like:
> 
> ```
> dnscollector_as_numbers_total{stream="global"} 1
> dnscollector_as_numbers_top_total{stream="global",domain="-"} 11977
> ```

I pushed a fix on metrics. But just to be sure, the GeoIP was enabled ? 
I ask that because the value "-" is the default one when no value are returned from geoip lookup.

**Comment by KVInventoR** [comment]
<img width="1198" alt="Screen Shot 2021-12-22 at 08 36 32" src="https://user-images.githubusercontent.com/9679368/147047030-c21eb76b-88b1-478d-b6f6-b6e5be7f3267.png">
I think AS db was loaded

probably it will be useful also to have output with number of loaded objects

**Comment by KVInventoR** [comment]
@dmachard 
is it possible to get a new docker image with bug fix?

**Comment by dmachard** [comment]
of course => the tag **v0.14.0-b2** is available.

**Comment by KVInventoR** [comment]
it works  &#128522;

**Comment by dmachard** [comment]
Regarding performance (cpu and memory), have you observe some differences?

**Comment by dmachard** [comment]
The release 0.14.0 is available.
