### ISSUE TITLE
TCP remote logger issue

### ISSUE THREAD

**Issue by anetrjuns** [dmachard/dns-collector#7]
I run the collector in another machine that the LB.

But when collector receive a frame the error message is logged 

INFO: 2021/11/08 18:06:55.225441 collector dnstap - ip:34116 - new connection
INFO: 2021/11/08 18:06:55.225563 dnstap processor - initialization...
INFO: 2021/11/08 18:06:55.225727 processor dnstap parser - running... waiting incoming dns message
ERROR: 2021/11/08 18:06:56.225753 collector dnstap - error stream receiver initialization: frame too large error

**Comment by dmachard** [comment]
could you share your config.yml ?

**Comment by anetrjuns** [comment]
[config.txt](https://github.com/dmachard/go-dnscollector/files/7502494/config.txt)

**Comment by dmachard** [comment]
thanks and also your config in dns server side for the dnstap part ?

**Comment by anetrjuns** [comment]
--DnsTap
fstl = newRemoteLogger("ip:6000")
addAction(AllRule(), DnstapLogAction("dnsdist03", fstl))
addResponseAction(AllRule(), DnstapLogResponseAction("dnsdist03", fstl))
-- Cache Hits
addCacheHitResponseAction(AllRule(), DnstapLogResponseAction("dnsdist03", fstl))

**Comment by dmachard** [comment]
I suspect TLS is enabled in the collector (tls-support: true), is it not?

**Comment by anetrjuns** [comment]
I have false for all tls-support fields.
	Line 25:     tls-support: false
	Line 149:     tls-support: false
	Line 197:     tls-support: false
	Line 215:     tls-support: false
	Line 256:     tls-support: false

**Comment by dmachard** [comment]
We are missing something because your case (dnsdist to collector) is used in [github actions](https://github.com/dmachard/go-dnscollector/runs/4162411237?check_suite_focus=true) and it works fine.

**Comment by anetrjuns** [comment]
Can you provide all the dependencies for dnscollector which must be installed on centos machine?

**Comment by dmachard** [comment]
You can follow the guide [here](https://dmachard.github.io/posts/0007-dnscollector-install-binary/), you just need to download the binary from github and push it in your centos machine.

**Comment by anetrjuns** [comment]
I follow the guide but install the collector in another machine that the dnsdist.

In your example you have installed dnsdist and collector on the same machine.

**Comment by dmachard** [comment]
I don't succeed to reproduce on my side, it works well in all cases.
can you take a network trace ?

**Comment by anetrjuns** [comment]
My collector and dnsdist is on the same subnet

**Comment by dmachard** [comment]
and have you try on the same machine ?
by the way what is the version of your dnsdist ?

**Comment by anetrjuns** [comment]
I don't have working dnsdist configuration with enabled newFrameStreamTcpLogger field. Every time service is failed with this error

dnsdist[3157]: Fatal Lua error: [string "chunk"]:24: Caught exception: fstrm with TCP support is required to build an AF_INET FrameStreamLogger
                                                 stack traceback:
                                                         [C]: in function 'newFrameStreamTcpLogger'
                                                         [string "chunk"]:24: in main chunk


dnsdist version is: 
dnsdist 1.6.0 (Lua 5.1.4 [LuaJIT 2.0.4])
Enabled features: cdb dns-over-tls(gnutls openssl) dns-over-https(DOH) dnscrypt fstrm ipcipher libsodium lmdb protobuf re2 recvmmsg/sendmmsg snmp systemd

**Comment by dmachard** [comment]
It's clear now, you must use the **newFrameStreamTcpLogger** to sent dnstap messages to the collector, I missed this point.

If your fstrm library does not support TCP and update is not possible, you can use newFrameStreamUnixLogger and follow this post
- dnsdist will write dnstap to the unixsocket
- stunnel read the unix socket and send dnstap messages to the collector with encrypted tunnel
- TLS is activated in the collector.

**Comment by anetrjuns** [comment]
when I  write dnstap to the unixsocket, is there any way to send dnstap message through a udp connection to dnscollector installed on another machine?

**Comment by dmachard** [comment]
only tcp+tls

**Comment by anetrjuns** [comment]
I have unstable stunnel on dnscollector side 
Every five second TLS session is going reset or rejected from dnscollector side
I'm attached the stunnel log from both dnsdist server
[dnsdist01_stunnel.txt](https://github.com/dmachard/go-dnscollector/files/7563945/dnsdist01_stunnel.txt)
[dnsdist02_stunnel.txt](https://github.com/dmachard/go-dnscollector/files/7563947/dnsdist02_stunnel.txt)

**Comment by dmachard** [comment]
could you try to add the following lines to your stunnel config ?

```
sslVersion = all
options = NO_SSLv2
options = NO_SSLv3
```

**Comment by anetrjuns** [comment]
I was try it, but result is the same

**Comment by dmachard** [comment]
on the dnsdist02, you have a network issue "connect_blocking: connect 10.1.1.11:6000: Connection refused (111)", perhaps firewall is enabled on your collector?

can you retry with ?

ciphers=EECDH+AESGCM:EDH+AESGCM
sslVersion = TLSv1.2
options = NO_SSLv2
options = NO_SSLv3

**Comment by anetrjuns** [comment]
I tried that too, the result is  the same
[dnsdist01_stunnel_01.txt](https://github.com/dmachard/go-dnscollector/files/7576143/dnsdist01_stunnel_01.txt)
![image](https://user-images.githubusercontent.com/37267191/142759965-0e988694-8655-4b0c-8261-d85b4e4e048d.png)

**Comment by dmachard** [comment]
Could you share the complete config of your stunnel and logs in dns collector side ?

**Comment by anetrjuns** [comment]
Yes sure.

chroot = /var/run/stunnel
setuid = dnsdist
setgid = dnsdist
pid = /stunnel.pid
debug = 7

; Some performance tunings
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1

ciphers=EECDH+AESGCM:EDH+AESGCM
sslVersion = TLSv1.2
options = NO_SSLv2
options = NO_SSLv3

[dnsdist-dnstaptls]
client=yes
accept=/var/run/stunnel/dnstap.sock
connect=10.16.32.11:6001

[dnstap_collector.txt](https://github.com/dmachard/go-dnscollector/files/7577031/dnstap_collector.txt)

**Comment by dmachard** [comment]
Could you take a network dump between your dnsdist and the collector ?

**Comment by anetrjuns** [comment]
Yes sure,

Pcap file size is 260MB, link to download it
https://wormhole.app/J3Kyx#RxBWODsnompUJkJ6i18OSA

![dnscollector_grafana](https://user-images.githubusercontent.com/37267191/143936145-17e7352e-911e-48b3-8952-d04d7fd41aeb.JPG)

**Comment by dmachard** [comment]
Thanks, finally can you also share the config of your dnscollector ?
Can you try to remove the following options on your stunnel ?

```
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
```

**Comment by anetrjuns** [comment]
[config.txt](https://github.com/dmachard/go-dnscollector/files/7631581/config.txt)

**Comment by dmachard** [comment]
thanks; same behaviour with the TCP_NODELAY option ?

**Comment by anetrjuns** [comment]
![image](https://user-images.githubusercontent.com/37267191/144221188-c35aacae-c8be-420d-a5fa-043636205c6e.png)

No, the result is the same

**Comment by dmachard** [comment]
If you want, can you try to use the dns-collector instead of stunnel ?
Deploy the dns collector in your dnsdist lb, configure-it to read the dnstap unix socket and forward to your remote dns collector 
Below a config example:

```
collectors:
  dnstap:
    enable: true
    sock-path: <replace_me_socket_path>
loggers:
  dnstap:
    enable: false
    remote-address: <replace_me_your_collector_ip>
    emote-port:  <replace_me_your_collector_port>
```

**Comment by dmachard** [comment]
@anetrjuns  A new release 0.14.0 is available, please to re-test with this version and apply my previous post.
Feel free to re-open the issue.
