### ISSUE TITLE
Kafka Group Support

### ISSUE THREAD

**Issue by Resha777** [dmachard/DNS-collector#908]
I'm using dnstap to capture requests from multiple dns servers then forward it to my kafka , the only issue is I can't specify which kafka group to send to , only topics , which is not enough for my use case , it would be great if you can implement it as an optional feature in the kafkaproducer, since you are already using kafka-go library , i think it would be easy for you. appreciate your support.

**Comment by dmachard** [comment]
I’m not sure I fully understand your request. As far as I know, groups are a concept primarily used on the consumer side in Kafka. Could you clarify what you mean by adding group support for the producer?

**Comment by Resha777** [comment]
Thank you for your response , It's true i managed to set it up in from the consumer side.
